<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "phpunitexample"
 *
 * Auto generated by Extension Builder 2018-10-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PHP Unit example',
    'description' => 'PHPUnit example',
    'category' => 'example',
    'author' => 'Christian Sonntag',
    'author_email' => 'pismo@web.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
